[package]
name = 'SupraVrf'
version = '1.0.0'

[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'dev'

[addresses]
supra_addr = "0x5c5f0d88231b581ab13d18c7bd42b21596b24dc6e96df7f7405bb18ac30514d7"
